### ISSUE TITLE
Clarifiaction?

### ISSUE THREAD

**Issue by sfabriece** [Salesflare/hapi-plugin-mysql#34]
What do you mean by the following? 
`If you have handlers that reply early, with reply.file() for example, be sure to register a tail event and use that as callback.`
Do I have to do anything after for ` reply('Ok');` in a route handler?

**Comment by AdriVanHoudt** [comment]
This is about doing stuff after you reply. See http://hapijs.com/api#requesttailname. This allows you to do database stuff with the connection after you replied. 
If you end your handler with just `reply('Ok')` you have nothing to worry about.

**Comment by sfabriece** [comment]
Thanks :)

**Comment by AdriVanHoudt** [comment]
No problem! Thanks for using the module!
