### ISSUE TITLE
Directly decorate the request object?

### ISSUE THREAD

**Issue by sfabriece** [Salesflare/hapi-plugin-mysql#35]
Is there a reason you chose to decorate the request 2 levels deep?

possibility for 

```
request.db
```

instead of

```
request.app.db
```

**Comment by AdriVanHoudt** [comment]
It mostly follows the hapi style guide. Just like `server.app`, `request.app` is made to put anything in you want. 

I did went back and looked at the api (http://hapijs.com/api#request-properties) and it does seem like it would be cleaner exposed as `request.plugins['hapi-plugin-mysql'].db` but that seems a bit convoluted. 

Another option would be to use http://hapijs.com/api#serverdecoratetype-property-method-options so you could do `request.getDb()`, `request.connection()`, `request.db()` or `request.getConnection()` or something which would allow just getting a connection when you need it. But you would have to manually close it like when using `server.getDb()` (unless I can find some way to store the connection in the plugin and close on tail somehow)

If you have any ideas/opinions on these options I would gladly listen to them. If there is going to be any change it would probably be the last one personally.

**Comment by sfabriece** [comment]
I totally agree on the last one, I'll try and see if there is a simple way of getting the last one to work without much change on the way it is currently being done.

**Comment by AdriVanHoudt** [comment]
PR's welcome ;) if you can find a way to auto close the connection I can add the request method and it won't even be a breaking change :D

**Comment by sfabriece** [comment]
I was looking at mysql modules docs, and it seems that you can use the pool directly without concerns of releasing the connection.
Would there been a downside of adding the pool to the request and removing it on the tail?

**Comment by AdriVanHoudt** [comment]
This plugin already uses a pool, you do have to tell the  mysql module you are done with a connection so the pool knows which connections are free to use again

**Comment by sfabriece** [comment]
This doesn't require a release of the connection, as it is on the pool directly.
```
Pooling connections

Use pool directly.

var mysql = require('mysql');
var pool  = mysql.createPool({
  connectionLimit : 10,
  host            : 'example.org',
  user            : 'bob',
  password        : 'secret'
});

pool.query('SELECT 1 + 1 AS solution', function(err, rows, fields) {
  if (err) throw err;

  console.log('The solution is: ', rows[0].solution);
});
```

**Comment by AdriVanHoudt** [comment]
That uses a connection per query (https://github.com/felixge/node-mysql/blob/1720920f7afc660d37430c35c7128b20f77735e3/lib/Pool.js#L184), while the plugin now gives you a connection per request.

**Comment by sfabriece** [comment]
Ahh I see. Let me play around and see what I can come up with.

Still interested in how you guard against db lost connection?

**Comment by AdriVanHoudt** [comment]
Not sure what you mean by db lost connection?

**Comment by sfabriece** [comment]
I mean how do you recover from the database being disconnect from your server?

**Comment by AdriVanHoudt** [comment]
atm this plugin throws since it assumes that you always have a connection if the first one works.
I could provide a function that get's called on error so you can gracefully handle it. Now with a pool if 1 connection fails it will remove it from the pool and try another one. see https://github.com/felixge/node-mysql#server-disconnects

**Comment by sfabriece** [comment]
It might be of interest, So ar I haven't thought of a way to handle the db server being disconnected.
I think your way might be the correct way to do it.

**Comment by AdriVanHoudt** [comment]
When I have time I'll look into adding this!
