### ISSUE TITLE
Feature request: use node-mysql2 instead of node-mysql 

### ISSUE THREAD

**Issue by sfabriece** [Salesflare/hapi-plugin-mysql#63]
It seems that there are some improvements that come from switching.

And node-mysql2 is api compatible with node-mysql.

https://github.com/sidorares/node-mysql2

**Comment by AdriVanHoudt** [comment]
I will accept a PR to pass in the desired mysql library, though the api needs to be the same (which is the case for node-mysql2 so 👍 )
